In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('ryai190138_appendixe1.xlsx')
df.describe()

/home/qtran/anaconda3/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,verse_ID,subject_ID,age_ct,CT_device,Res,BMD,DXA T-value,N_vertebrae,foreign_material,N_Fx,...,T2_fx-s,T3_fx-s,T4_fx-s,T5_fx-s,T6_fx-s,T7_fx-s,T8_fx-s,T9_fx-s,T10_fx-s,L6_fx-s
count,160.000000,160.000000,160.000000,160.000000,160.000000,160.000000,108.000000,160.00000,160.000000,160.000000,...,70.000000,61.000000,61.000000,60.000000,60.000000,63.000000,66.00000,81.000000,88.000000,6.0
mean,132.200000,171.106250,63.982437,2.462500,1.628125,83.104375,-1.546296,10.78125,0.193750,1.806250,...,0.071429,0.295082,0.131148,0.216667,0.200000,0.333333,0.30303,0.234568,0.170455,0.0
std,88.441275,144.954193,16.289194,1.288007,0.682778,57.007932,1.783383,5.29824,0.772946,2.348549,...,0.353919,0.738112,0.464593,0.640224,0.546173,0.718421,0.67868,0.597319,0.530053,0.0
min,4.000000,4.000000,18.890000,1.000000,1.000000,0.000000,-5.500000,1.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0
25%,58.750000,58.750000,56.100000,1.000000,1.000000,40.325000,-2.900000,6.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0
50%,112.500000,114.500000,65.950000,2.000000,2.000000,71.050000,-1.700000,9.00000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0
75%,223.500000,265.250000,76.342500,4.000000,2.000000,120.225000,-0.475000,17.00000,0.000000,3.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0
max,290.000000,417.000000,90.560000,5.000000,3.000000,238.200000,3.300000,24.00000,5.000000,12.000000,...,2.000000,3.000000,2.000000,3.000000,3.000000,3.000000,3.00000,3.000000,2.000000,0.0

In [3]:
df = df.replace(['x'],5)
df.fillna(-1)

,verse_ID,subject_ID,dataset,age_ct,CT_device,Res,BMD,DXA T-value,CT_image_series,N_vertebrae,...,T9_fx-s,T10_fx-s,T11_fx-s,T12_fx-s,L1_fx-s,L2_fx-s,L3_fx-s,L4_fx-s,L5_fx-s,L6_fx-s
0,12,12,test secret,77.40,3,3.0,61.3,0.2,1 of 1,6,...,-1.0,0.0,0.0,0.0,1.0,0.0,2.0,-1.0,-1.0,-1.0
1,20,20,test secret,85.80,1,2.0,0.0,-2.1,1 of 1,17,...,3.0,0.0,2.0,0.0,3.0,2.0,2.0,0.0,0.0,-1.0
2,29,29,test secret,50.60,2,3.0,106.6,-1.8,1 of 1,17,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0
3,32,32,test secret,83.30,4,2.0,89.6,1.0,1 of 1,6,...,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0,5.0,-1.0
4,38,38,test secret,54.10,2,3.0,70.4,-3.7,1 of 1,7,...,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,256,404,validation public,59.07,4,2.0,138.2,-1.0,2 of 2,18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0
156,264,264,validation public,29.34,3,1.0,142.8,-1.0,1 of 1,17,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.0
157,269,269,validation public,41.28,2,1.0,96.1,-1.0,1 of 1,16,...,2.0,2.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,-1.0
158,276,276,validation public,74.27,5,2.0,109.2,-1.0,1 of 1,18,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-1.0
159,290,412,validation public,46.45,2,1.0,118.3,-1.0,2 of 2,19,...,1.0,0.0,0.0,1.0,1.0,1.0,2.0,0.0,0.0,-1.0

In [4]:
import sweetviz as sv

report = sv.analyze(df)
report.show_html()

                                             |          | [  0%]   00:00 -> (? left)

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [5]:
# from pandas_profiling import ProfileReport
# profile = ProfileReport(df, title='Report', explorative = True)
# profile.to_file("verse2019.html")
# profile

In [6]:
# ! pip install sweetviz

In [7]:
# ! pip install pandas-profiling

# #Enable the widget extension in Jupyter
# !jupyter nbextension enable --py widgetsnbextension

In [8]:
df

,verse_ID,subject_ID,dataset,age_ct,CT_device,Res,BMD,DXA T-value,CT_image_series,N_vertebrae,...,T9_fx-s,T10_fx-s,T11_fx-s,T12_fx-s,L1_fx-s,L2_fx-s,L3_fx-s,L4_fx-s,L5_fx-s,L6_fx-s
0,12,12,test secret,77.40,3,3.0,61.3,0.2,1 of 1,6,...,NaN,0.0,0.0,0.0,1.0,0.0,2.0,NaN,NaN,NaN
1,20,20,test secret,85.80,1,2.0,0.0,-2.1,1 of 1,17,...,3.0,0.0,2.0,0.0,3.0,2.0,2.0,0.0,0.0,NaN
2,29,29,test secret,50.60,2,3.0,106.6,-1.8,1 of 1,17,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,32,32,test secret,83.30,4,2.0,89.6,1.0,1 of 1,6,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5.0,NaN
4,38,38,test secret,54.10,2,3.0,70.4,-3.7,1 of 1,7,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,256,404,validation public,59.07,4,2.0,138.2,NaN,2 of 2,18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
156,264,264,validation public,29.34,3,1.0,142.8,NaN,1 of 1,17,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN
157,269,269,validation public,41.28,2,1.0,96.1,NaN,1 of 1,16,...,2.0,2.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,NaN
158,276,276,validation public,74.27,5,2.0,109.2,NaN,1 of 1,18,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
159,290,412,validation public,46.45,2,1.0,118.3,NaN,2 of 2,19,...,1.0,0.0,0.0,1.0,1.0,1.0,2.0,0.0,0.0,NaN